#!/usr/bin/env python
import os
CHECK_FILE_EXT = ['r', 'R', 'hx', 'js', 'py']
DIR = 'src'

def check_newline_eof(path):
        
        files = []
        for p in os.listdir(path):
                f = os.path.join(path, p)
                if os.path.isdir(f):
                        check_newline_eof(f)
                        continue
                ext = p.split('.')[-1]
                if ext in CHECK_FILE_EXT:
                        fo = open(f, 'r')
                        try:
                                fo.seek(-1, 2)
                        except:
                                continue
                        if fo.read(1) != '\n':
                                files += [f]
        
        return files

files_without_newline_at_eof = check_newline_eof(DIR)

if len(files_without_newline_at_eof) > 0:
        print('Please add newline at the end of this files:')
        for f in files_without_newline_at_eof:
                print(f)
        os.sys.exit(1)
